### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Derpolino** [fewfre/TransformiceDressroom#2]
Where is the button to get the link of the look ?

**Comment by fewfre** [comment]
It's disabled since it wasn't working. I'll probably add it next time I get around to dressing rooms.

**Comment by fewfre** [comment]
So looked into it and another reason I disabled it is having to keep track of custom colors and stuff in the "other" tab, both of which is currently in. Not impossible / especially hard, just a bit of a pain.

**Comment by fewfre** [comment]
Fixed
