### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by JoaoMXN** [fewfre/TransformiceDressroom#5]
It's possible to put the prices of all items in the dressroom? And put a zoom that makes the items more big to download/view?

**Comment by fewfre** [comment]
No, the prices for the items is not possible without me having to manually add them each time (which I'm not willing to do); can't be done with an update script.

Do you mean a zoom for the normal download (the entire mouse) or for the individual item download button on top right? If the former than it already does/should export it at whatever scale you picked. If the later, I can look into it; I probably won't add a an option in the dressroom, but could add a "&scale=" url variable that would control it.

**Comment by JoaoMXN** [comment]
I mean the zoom with the slider. Even maxed out the zoom is very low.

https://i.imgur.com/C3za2Jl.png

**Comment by fewfre** [comment]
Odd, I swore that used to be a lot higher. Well since I'm adding something this weekend anyways, I'll make sure to increase that!

**Comment by fewfre** [comment]
Alright, you can now scale up to twice as much as before! Sorry I can't do anything about the prices, you're not the only one to have asked, so I know it's a desired featured.
